# Site settings
title: Projet Louvre INA en test
email: your-email@domain.com
description:   Ceci est un espace pour mon Edito ...youpi :)
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nicolegerbault
github_username:  nicolegerbault

# Build settings
markdown: kramdown
